
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: local  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/fcardone/Work/artigiancassa/prod/gal/k8s/pv_nb/minio/data"  # Cambia questo percorso con il percorso reale sul tuo host
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    kind: PersistentVolumeClaim
    namespace: databases
    name: minio-pvc
    apiVersion: v1

---
