nelmio_security:
    csp:
        enforce:
            default-src: [ 'self' ]
            script-src: [ 'self', 'https://code.jquery.com', 'https://cdnjs.cloudflare.com' ]
            img-src: [ 'self', 'https://www.w3.org']
            style-src: [ 'self', 'https://code.jquery.com', 'https://cdnjs.cloudflare.com']
