App\Entity\Application:
    fields:
        id: ID
        practiceId: 'Codice Pratica Confidi'
        flagEnergia: 'Energia'
        aeGAssuranceAmount: 'Importo Garanzia Confidi'
        aeGResolutionDate: 'Data Delibera Confidi'
#        aeAcCommissionsRebateRequest: 'Richiesta Abbuono Commissioni'
#        aeAcInterestsContributionRequest: 'Richiesta Contributo Interessi/Canoni'
#        aeAcLostFundContributionRequest: 'Richiesta Contributo Fondo Perduto'
#        aeAcContributionApplicationAmount: 'Importo Domanda di Contributo'
#        aeAcApplicationMembers: 'Numero Soci Partecipanti alla Domanda'

        aeIbBusinessName: 'Ragione Sociale'
        aeIbFiscalCode: 'Codice Fiscale'
#        aeIbSize: 'Dimensione'
        aeIbConstitutionDate: 'Data Costituzione'
        aeIbChamberOfCommerceCode: 'Codice Iscrizione Camera di commercio'
#        aeIbChamberOfCommerceRegistrationDate: 'Data Iscrizione Camera di Commercio'
        aeIbAIACode: 'Codice AIA'
#        aeIbAIARegistrationDate: 'Data Iscrizione AIA'
        aeIbAtecoCode: 'Codice Attività ATECO'
#        aeIbAtecoStartDate: 'Data Inizo Attività ATECO'
        aeIbIban: 'Codice IBAN'
        aeIbLegalForm: 'Forma Giuridica'
        aePecAddress: 'Indirizzo PEC'
        aeOfficeAddress: 'Indirizzo Sede Legale'
        aeOfficePostcode: 'CAP Sede Legale'
        aeOfficeCity: 'Comune Sede Legale'
        aeWorkplaceAddress: 'Indirizzo Sede Operativa'
        aeWorkplacePostcode: 'CAP Sede Operativa'
        aeWorkplaceCity: 'Comune Sede Operativa'

#        aeOwnerLastname: 'titolare - Cognome'
#        aeOwnerFirstname: 'titolare - Nome'
#        aeOwnerBirthDate: 'titolare - Data Nascita'
#        aeOwnerGender: 'titolare - Sesso'
#        aeOwnerFiscalCode: 'titolare - Codice Fiscale'
#        aeOwnerBirthCity: 'titolare - Comune di Nascita (se in Italia)'
#        aeOwnerBirthCountry: 'titolare - Stato Estero di Nascita'
#        aeOwnerJoinDate: 'titolare - Data Aggregazione all’impresa'
#        aeFirstMemberLastname: 'altro componente 1 - Cognome'
#        aeFirstMemberFirstname: 'altro componente 1 - Nome'
#        aeFirstMemberBirthDate: 'altro componente 1 - Data Nascita'
#        aeFirstMemberGender: 'altro componente 1 - Sesso'
#        aeFirstMemberFiscalCode: 'altro componente 1 - Codice Fiscale'
#        aeFirstMemberBirthCity: 'altro componente 1 - Comune di Nascita (se in Italia)'
#        aeFirstMemberBirthCountry: 'altro componente 1 - Stato Estero di Nascita'
#        aeFirstMemberJoinDate: 'altro componente 1 - Data Aggregazione all’impresa'
#        aeSecondMemberLastname: 'altro componente 2 - Cognome'
#        aeSecondMemberFirstname: 'altro componente 2 - Nome'
#        aeSecondMemberBirthDate: 'altro componente 2 - Data Nascita'
#        aeSecondMemberGender: 'altro componente 2 - Sesso'
#        aeSecondMemberFiscalCode: 'altro componente 2 - Codice Fiscale'
#        aeSecondMemberBirthCity: 'altro componente 2 - Comune di Nascita (se in Italia)'
#        aeSecondMemberBirthCountry: 'altro componente 2 - Stato Estero di Nascita'
#        aeSecondMemberJoinDate: 'altro componente 2 - Data Aggregazione all’impresa'
#        aeThirdMemberLastname: 'altro componente 3 - Cognome'
#        aeThirdMemberFirstname: 'altro componente 3 - Nome'
#        aeThirdMemberBirthDate: 'altro componente 3 - Data Nascita'
#        aeThirdMemberGender: 'altro componente 3 - Sesso'
#        aeThirdMemberFiscalCode: 'altro componente 3 - Codice Fiscale'
#        aeThirdMemberBirthCity: 'altro componente 3 - Comune di Nascita (se in Italia)'
#        aeThirdMemberBirthCountry: 'altro componente 3 - Stato Estero di Nascita'
#        aeThirdMemberJoinDate: 'altro componente 3 - Data Aggregazione all’impresa'
#        aeFourthMemberLastname: 'altro componente 4 - Cognome'
#        aeFourthMemberFirstname: 'altro componente 4 - Nome'
#        aeFourthMemberBirthDate: 'altro componente 4 - Data Nascita'
#        aeFourthMemberGender: 'altro componente 4 - Sesso'
#        aeFourthMemberFiscalCode: 'altro componente 4 - Codice Fiscale'
#        aeFourthMemberBirthCity: 'altro componente 4 - Comune di Nascita (se in Italia)'
#        aeFourthMemberBirthCountry: 'altro componente 4 - Stato Estero di Nascita'
#        aeFourthMemberJoinDate: 'altro componente 4 - Data Aggregazione all’impresa'

        fDbfBank: 'finanziamento - Banca'
#        fDbfBusinessName: 'finanziamento - Codice Fiscale - Ragione Sociale'
#        fDbfABI: 'finanziamento - ABI'
#        fFFinancialDestination: 'finanziamento - Finalità finanziamento'
        fFinancialDestination: 'finanziamento - Finalità finanziamento'
        fDfAmount: 'finanziamento - Importo Finanziamento'
        fDfContractSignatureDate: 'finanziamento - Data Firma Contratto'
#        fDfResolutionDate: 'finanziamento - Data Delibera'
        fDfIssueDate: 'finanziamento - Data Erogazione'
        fDfDuration: 'finanziamento - Durata Finanziamento'
#        fDfLoanProvidedAtImport: 'finanziamento - Finanziamento già erogato' # // TODO verificare se serve
#        fDfPeriodicity: 'finanziamento - Periodicità Rate'
#        fDfFirstDepreciationDeadline: 'finanziamento - Data Scadenza Prima Rata Ammortamento'
#        fDfPreDepreciationExists: 'finanziamento - Esiste Preammortamento'
#        fDfInstallmentAmount: 'finanziamento - Importo Rata'
#        fTRateType: 'finanziamento - Tipologia Tasso'
#        fTRate: 'finanziamento - Tasso'
#        fTTaeg: 'finanziamento - Taeg'

        lSfBankLeasing: 'leasing - Banca o Società di Leasing'
#        lSfBusinessName: 'leasing - Codice Fiscale - Ragione Sociale'
        lSfLeasingDestination: 'leasing - Finalità locazione'
        lDclAmount: 'leasing - Importo Leasing'
        lDclContractSignatureDate: 'leasing - Data Firma Contratto'
#        lDclResolutionDate: 'leasing - Data Delibera'
        lDclDuration: 'leasing - Durata Leasing'
#        lDclPeriodicity: 'leasing - Periodicità canone'
        lDclFirstDeadline: 'leasing - Data Scadenza Primo Canone'
#        lDclFeeAmount: 'leasing - Importo Canone Periodico (comprensivo di spese aggiuntive)'
        lDclFeePercentage: 'leasing - Percentuale macrocanone'
        lDclRansomPercentage: 'leasing - Percentuale Riscatto'

        protocolNumber: 'Protocollo Domanda'
        protocolDate: 'Data Protocollo'
        status: 'RIASS - Stato' # mettere la descrizione
        nsiaNumeroPosizione: 'RIASS - Numero Posizione'
#        nsiaDataProtocollo: '$nsiaDataProtocollo'
        nsiaNota: 'RIASS - Nota'
        nsiaDataDelibera: 'RIASS - Data Delibera Posizione'
        nsiaCodiceCor: 'RIASS - Codice COR'
#        nsiaDataRilascioCor: '$nsiaDataRilascioCor'
#        nsiaLDclImportoRiscatto: '$nsiaLDclImportoRiscatto'
#        nsiaDurataGaranzia: '$nsiaDurataGaranzia'
        nsiaImportoRiassicurazione: 'RIASS - Importo Riassicurazione'
        nsiaEslRiassicurazione: 'RIASS - Importo ESL'
        nsiaDataInizioGaranzia: 'RIASS - Data Inizio Garanzia'
        nsiaDataFineGaranzia: 'RIASS - Data Fine Garanzia'
#        nsiaDataLiquidazioneConfidi: '$nsiaDataLiquidazioneConfidi'
#        nsiaImportoPerditaConfidi: '$nsiaImportoPerditaConfidi'
#        nsiaDataRichiestaRimborso: '$nsiaDataRichiestaRimborso'
        nsiaDataProtocolloPerdita: 'RIASS - Data protocollo richiesta rimborso'
#        nsiaDataDeliberaPerdita: '$nsiaDataDeliberaPerdita'
#        nsiaImportoRimborsoPrenotato: '$nsiaImportoRimborsoPrenotato'
        nsiaImportoRimborsato: 'RIASS - Importo Rimborsato'
        nsiaDataLiquidazione: 'RIASS - Data Liquidazione Perdita'
#        nsiaImportoRestituitoConfidi: '$nsiaImportoRestituitoConfidi'
#        nsiaDataRestituzioneConfidi: '$nsiaDataRestituzioneConfidi'

App\Entity\AdditionalContribution:
    fields:
        id: 'Abbuono Richiesto' # (metter un si o un no o una crocetta…)
#        type: '$type'
        presentationDate: ' Data Richiesta'
#        inImport: '$inImport'
        nsiaNumeroPosizione: 'Numero Posizione'
        nsiaStatus: 'Stato' # mettere la descrizione
        nsiaNota: 'Nota'
        nsiaDataDelibera: 'Data Delibera'
        nsiaCodiceCor: 'Codice COR'
#        nsiaDataRilascioCor: '$nsiaDataRilascioCor'
        nsiaImportoContributoDeliberato: 'Importo Deliberato'
        nsiaImportoContributoLiquidato: 'Importo liquidato'
        nsiaDataLiquidazione: 'Data Liquidazione'
#        nsiaIbanLiquidazione: '$nsiaIbanLiquidazione'
        nsiaDataRevoca: 'Data Revoca'
        nsiaMotivoRevoca: 'Motivo Revoca'
        nsiaImportoContributoRevocato: 'Importo Revocato'
#        nsiaDataAvvioProcedimentoRevoca: '$nsiaDataAvvioProcedimentoRevoca'
        nsiaImportoRecuperoDovuto: 'Importo da Restituire'
#        nsiaInteressiDovuti: '$nsiaInteressiDovuti'
#        nsiaDataRichiestaRecupero: '$nsiaDataRichiestaRecupero'
        nsiaImportoContributoRestituito: 'Importo restituito'
#        nsiaImportoInteressiRestituiti: '$nsiaImportoInteressiRestituiti'
#        nsiaDataRestituzione: '$nsiaDataRestituzione'
